import "../../app/globals.css";
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] });
import AuthProvider from "@/context/AuthProvider";
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en"  className={inter.className}>
          <AuthProvider>
      <body>{children}</body>
      </AuthProvider>
    </html>
  )
}
