import "./globals.css";
import type { Metadata } from "next";
import AuthProvider from "./context/AuthProvider";
import { Inter } from 'next/font/google'
 
// Initialize the Inter font
const inter = Inter({ 
  subsets: ['latin'],
  variable: '--font-inter',
});

// Then in your layout:

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${inter.variable} font-sans`}>
      <body className={inter.className}>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}